### PR TITLE
Add docker compose to backend

### PR DESCRIPTION
**Pull request by gordalina**
This replaces the current docker compose configuration.

It adds nhost, neo4j, hasura-cli and the api in a docker compose enviornment so one can run the full stack locally.

@nohea I wasn't able to test gedcom files, could you have a go at them?

### CODE REVIEW

**Comment by nohea** [comment]
on my Linux box (ubuntu 20.04), i get:
```
raulg@ashy:~/Documents/code/hawaiiansintech/mookuauhau-backend$ docker compose up
docker: 'compose' is not a docker command.
See 'docker --help'
```
i use docker-compose instead:
```
WARNING: The NEO4J_USER variable is not set. Defaulting to a blank string.
WARNING: The NEO4J_PASS variable is not set. Defaulting to a blank string.
WARNING: The HASURA_GRAPHQL_JWT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_SECRET_KEY variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.hasura-cli: 'profiles'
```
If i set all the missing vars in .dev, i still get:
```
$ docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.hasura-cli: 'profiles'
```

**Comment by nohea** [comment]
i have an old version:

```
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

https://forums.docker.com/t/unsupported-config-option-for-services-profiles/103767

**Comment by nohea** [comment]
i've determined i need to update:
https://docs.docker.com/engine/install/ubuntu/

i'll do this, i didn't even know there is Docker Desktop for Linux

**Comment by nohea** [comment]
I got the containers running after changing the psql port (conflicted w/my 5432). 
Loader scripts failed due to package.json changes to the run commands, replacements w/ts-node-esm. 
When i changed back, i could load to the neo4j instance. 
Need to check out other things later, lot of changes...

**Comment by gordalina** [comment]
I did change the loader scripts so they are run via docker, see the info in README:

```sh
docker compose run --rm api npm run tgql

# or any other script
```

Happy to revert those if there's issues with it

**Comment by nohea** [comment]
> I did change the loader scripts so they are run via docker, see the info in README:

I think its overkill for developers. But thanks for the ts-node-esm education, i'm still ramping up on typescript. 

I'm making changes today based on this PR. I do think the nhost docker will be too heavyweight/complex for most, that's why i made a stripped down hasura+pg. Also i think neo4j should be split separate. Most will use one or the other. 

Finally the reason for ENV vars in the docker-compose.yaml is for hasura metadata exports/apply scripts. If the export is from a container, you can't apply the metadata to production otherwise pain! So the practice i set up was to use .env in the ./hasura-docker dir, but i could combine in the root project .env

**Pull request merged**
